# Generated by Django 6.1.1 on 2026-09-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='datasets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile_data', models.JSONField(blank=True, null=True)),
                ('kpi_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
